import { Assets } from '../../Assets/Assets';

const PropertyList = [
        {
            Id: 1,
            Image: Assets.hostel_1,
            Address: "PG-1 at Vadapalani",
            RoomAddress: "9/1A, Saidapet Rd, near V.K Enterprises, Sarvamangala Colony, Aruna Colony, Vadapalani, Chennai, Tamil Nadu 600026",
            Title: "Rent starts from",
            Title1: "Starting from",
            Brand: "Brindhavanam",
            Rent: "Rs: 6,500/-",
            Tag: "Male",
            Button: "View More",
            Image1: Assets.home_1_1_img,
            Image2: Assets.home_1_2_img,
            Image3: Assets.home_1_3_img,
            Image4: Assets.home_2_1_img,
            Image5: Assets.home_2_2_img,
            Image6: Assets.home_2_3_img,
            Method1: "Two Sharing",
            Method2: "Three Sharing",
            Method3: "Four & Five Sharing",
            Method4: "Six & Eight Sharing",
            Method5: "Four Sharing",
            Method6: "Eight Sharing",
            Rent1: "₹ 8000",
            Rent2: "₹ 7500",
            Rent3: "₹ 7000",
            Rent4: "₹ 6500",
            Rent5: "₹ 8000",
            Rent6: "₹ 7000",
            Fac1: "Ac",
            Fac2: "Non-Ac",
            AboutInfo: "Bid farewell to your discomfort. Wave goodbye to mundane PG accommodations and welcome the world of Brindhavanam Hi Tech mens PG's. Here, you'll unlock the doors to fully furnished.",
            RoomInfo: "All room type have some variants that are larger in size or have extra Amenities.",
            FoodInfo: "Veg and weekly once Non-veg",
            PayInfoTitle: "Electricity Charges: Based On Actuals",
            PayInfoContent: "As applicable under the relevant State Electricity Board Charges, plus necessary convenience charges wherever applicable.Electicity charges are not included in the monthly payment.",
            PayInfoSubTitle: "Maintenance Charges: NIL",
            PayInfoSubContent: "No Maintenance Charges. Any loss or damage to the Property is subjected to the deduction in Security Deposit."
        },
        {
            Id: 2,
            Image: Assets.hostel_2,
            Address: "PG at Ramapuram",
            Title: "Rent starts from",
            Brand: "Brindhavanam",
            Rent: "Rs: 12,500/-",
            Tag: "Male",
            Button: "View More",
            Image1: Assets.home_3_1_img,
            Image2: Assets.home_3_2_img,
            Image3: Assets.home_3_3_img,
            Image4: Assets.home_4_1_img,
            Image5: Assets.home_4_2_img,
            Image6: Assets.home_1_3_img,
            AboutInfo: "Bid farewell to your discomfort. Wave goodbye to mundane PG accommodations and welcome the world of Brindhavanam Hi Tech mens PG's. Here, you'll unlock the doors to fully furnished.",
            RoomInfo: "All room type have some variants that are larger in size or have extra Amenities.",
            PayInfoTitle: "Electricity Charges: Based On Actuals",
            PayInfoContent: "As applicable under the relevant State Electricity Board Charges, plus necessary convenience charges wherever applicable.Electicity charges are not included in the monthly payment.",
            PayInfoSubTitle: "Maintenance Charges: NIL",
            PayInfoSubContent: "No Maintenance Charges. Any loss or damage to the Property is subjected to the deduction in Security Deposit."
        },
        {
            Id: 3,
            Image: Assets.hostel_3,
            Address: "Guest House at Vadapalani",
            RoomAddress: "9/1A, Saidapet Rd, near V.K Enterprises, Sarvamangala Colony, Aruna Colony, Vadapalani, Chennai, Tamil Nadu 600026",
            Title: "Rent starts from",
            Brand: "Brindhavanam",
            Rent: "Rs: 8,000/-",
            Tag: "Male",
            Button: "View More",
            Image1: Assets.home_3_1_img,
            Image2: Assets.home_3_2_img,
            Image3: Assets.home_3_3_img,
            Image4: Assets.home_4_1_img,
            Image5: Assets.home_4_2_img,
            Image6: Assets.home_1_3_img,
            AboutInfo: "Bid farewell to your discomfort. Wave goodbye to mundane PG accommodations and welcome the world of Brindhavanam Hi Tech mens PG's. Here, you'll unlock the doors to fully furnished.",
            RoomInfo: "All room type have some variants that are larger in size or have extra Amenities.",
            PayInfoTitle: "Electricity Charges: Based On Actuals",
            PayInfoContent: "As applicable under the relevant State Electricity Board Charges, plus necessary convenience charges wherever applicable.Electicity charges are not included in the monthly payment.",
            PayInfoSubTitle: "Maintenance Charges: NIL",
            PayInfoSubContent: "No Maintenance Charges. Any loss or damage to the Property is subjected to the deduction in Security Deposit.",
            BreakfastTime: "- Breakfast - 08:00AM - 10:00AM",
            LunchTime: "- Lunch - 1:30PM - 3:00PM",
            DinnerTime: "- Dinner - 8:00PM - 9:30PM"

        },
        {
            Id: 4,
            Image: Assets.hostel_4,
            Address: "Large at Ramapuram",
            Title: "Rent starts from",
            Brand: "Brindhavanam",
            Rent: "Rs: 8,000/-",
            Tag: "Male",
            Button: "View More",
        },
        {
            Id: 5,
            Image: Assets.hostel_5,
            Address: "Appartment at Kodambakkam",
            Title: "Rent starts from",
            Brand: "Brindhavanam",
            Rent: "Rs: 12,000/-",
            Tag: "Male",
            Button: "View More",
        },
        {
            Id: 6,
            Image: Assets.hostel_1,
            Address: "PG-2 at Vadapalani",
            Title: "Rent starts from",
            Brand: "Brindhavanam",
            Rent: "Rs: 6,500/-",
            Tag: "Male",
            Button: "View More",
            Image1: Assets.home_3_1_img,
            Image2: Assets.home_3_2_img,
            Image3: Assets.home_3_3_img,
            Image4: Assets.home_4_1_img,
            Image5: Assets.home_4_2_img,
            Image6: Assets.home_1_3_img,
            AboutInfo: "Bid farewell to your discomfort. Wave goodbye to mundane PG accommodations and welcome the world of Brindhavanam Hi Tech mens PG's. Here, you'll unlock the doors to fully furnished.",
            RoomInfo: "All room type have some variants that are larger in size or have extra Amenities.",
            FoodInfo: "Veg and weekly once Non-veg",
            PayInfoTitle: "Electricity Charges: Based On Actuals",
            PayInfoContent: "As applicable under the relevant State Electricity Board Charges, plus necessary convenience charges wherever applicable.Electicity charges are not included in the monthly payment.",
            PayInfoSubTitle: "Maintenance Charges: NIL",
            PayInfoSubContent: "No Maintenance Charges. Any loss or damage to the Property is subjected to the deduction in Security Deposit."
        }
    ]

export default PropertyList;
